### ISSUE TITLE
What if the cluster has unreachable node, but without the leader in the quorum?

### ISSUE THREAD

**Issue by lejoow** [mbilski/akka-reasonable-downing#1]
Hello Mbliski,

Thanks for the nice library.

I have a quick question in the downing logic.

# Situation:

You have three nodes [A,B,C] in the cluster, and node C is currently acting as the leader of the cluster. 
Then suddenly, the node **C becomes unreachable** while Node A and B can still talk to each other. 

But because the quorum size is 2, node C will down itself after the timeout, and node A and B will remain in the cluster.

Nodes = [A,B,C]
Quorum = 2
Leader = C

# Question:

According to the below _**checkQuorum**_ logic, I have a doubt that Node A and B will not be able to down the Node C, hence, the cluster will NOT be able to achieve the "Gossip Converge" indefinitely.

Let's say the below logic was executed in Node A and B.

It will pass thru the first logic because unreachable size is 1, and the quorum size is 2 (only Node C is unreachable).

It will pass the second logic because reachable size is 2 (A and B are reachable to each other), and the quorum size is 2, hence reachable.size < settings.quorum is false.

It will also pass the last logic because although the "cluster.state.unreachable.nonEmpty"is true, neither of the nodes A and B are the leader.

So even if the below logic results in Node C to down itself, because neither of Node A and Node B is the leader of the cluster, Node C will still remain as "unreachable" to Node A and Node B.

Is my understanding of the logic correct?
If so, isn't this going to be a problem?

Thank,

Joo
```

  def checkQuorum(): Unit =
    if (unreachable.size >= settings.quorum) {
      log.warning("Downing reachable nodes because of {} unreachable nodes [{}]",
                  settings.quorum,
                  cluster.state)
      reachable.map(_.address).foreach(cluster.down)
    } else if (reachable.size < settings.quorum) {
      log.warning("Downing reachable nodes because of too small cluster {} [{}]",
                  reachable,
                  cluster.state)
      reachable.map(_.address).foreach(cluster.down)
    } else if (cluster.state.unreachable.nonEmpty && isLeader) {
      log.warning("Downing unreachable nodes {} [{}]", unreachable, cluster.state)
      unreachable.map(_.address).foreach(cluster.down)
    }
```

**Comment by mbilski** [comment]
Hi Joo,

Yes, your understanding is correct, but only in a case when a new leader is not elected when the other nodes observe the current leader as unreachable.

However, in akka cluster when a current leader is unreachable, the other nodes elect a new leader. So he can mark the unreachable node as down (using split brain resolver). See this screencast https://www.youtube.com/watch?v=_uz8QOjVrNQ
 
You can find the sources for this demo here https://github.com/mbilski/akka-downing-example

Regards,
Mateusz

PS. I just found this article https://medium.com/stashaway-engineering/running-a-lagom-microservice-on-akka-cluster-with-split-brain-resolver-2a1c301659bd Yeah, I agree that the docs can be confusing https://doc.akka.io/docs/akka/snapshot/common/cluster.html

**Comment by lejoow** [comment]
The screencast is very helpful! Thanks a lot.

Have you considered adding the "**else**" statement at the last to throw the exception or log the error to indicate what the actual problem is? Right now, that tricky (and perhaps technically impossible) case where the no new leader was elected but the network partition has occurred is not handled anywhere in the method (maybe just for the better readability even if that case is impossible to happen). 

Maybe I should create a PR? =)

As well, I am discussing this issue with the Akka team lead from Lightbend at this thread [here](https://groups.google.com/forum/#!topic/lagom-framework/-wwR7tCcatE). They are super responsive and very supportive - probably one of the best channels to speak with the Lightbend team on various technical topics at the moment.

Please feel free to jump in and add your thoughts.

 Many thanks!

**Comment by mbilski** [comment]
@lejoow please take a look at #2. I improved verbosity a bit. If it's fine for you, I will close this issue, after merging that PR.

**Comment by lejoow** [comment]
Thank you @mbilski, will take a look shortly!
