### ISSUE TITLE
Should a node wait a bit for downing if there are unreachable nodes but no leader?

### ISSUE THREAD

**Issue by thomschke** [mbilski/akka-reasonable-downing#10]
Hi mbilski,

There is a tricky situation, where unreachable nodes exists but there is no leader for downing them:
https://github.com/mbilski/akka-reasonable-downing/blob/763613676fc5eb0d6c5e625c68ec8840b79f4e77/src/main/scala/pl/immutables/akka/reasonable/downing/StaticQuorumDowning.scala#L131-L135

Would not it be better to wait something and check again instead of downing them immediately? So in the meantime the leader election can perform.

**Comment by mbilski** [comment]
Hi thomschke,

the resolver already waits ${akka.reasonable.downing.stable-after} seconds (by default 7s) before making the decision. I think adding more wait here won't help. 

I added a fix for your's another issue #9. This should fix this case.
