### ISSUE TITLE
checkIfClusterStarted  may be not correct.

### ISSUE THREAD

**Issue by frubby** [mbilski/akka-reasonable-downing#4]
checkIfClusterStarted  is executed when  received a MemberUp event , then in checkIfClusterStarted use cluster.state to get and filter started Member count .
The problem is sometimes the count is not correct  : received a MemberUp event ,but Member Up node's count is not already current count,(I found is realCount -1 ),may be cluster.state is not sync when received a MemberUp Event. This result the node will never become startedCluster and  it will never run the checkQuorum logic.

There is akka doc say:(at bottom of chapter  https://doc.akka.io/docs/akka/current/cluster-usage.html#subscribe-to-cluster-events)
_Instead of subscribing to cluster events it can sometimes be convenient to only get the full membership state with Cluster.get(system).state(). Note that this state **is not necessarily in sync with the events** published to a cluster subscription._ 

so how to solve this problem, is it need some delay time to checkIfClusterStarted , or we record MembersUp count by my self instead of use cluster.state?

**Comment by mbilski** [comment]
@frubby You're right. I created a pull request with a fix for this issue #5. Please take a look.
