### ISSUE TITLE
Should each non-leader node only downing itself?

### ISSUE THREAD

**Issue by thomschke** [mbilski/akka-reasonable-downing#9]
Hi mbilski,

I like your SBR !

But there are three situations where _NON_-leading nodes are downing _ALL_ problematic members:

https://github.com/mbilski/akka-reasonable-downing/blob/763613676fc5eb0d6c5e625c68ec8840b79f4e77/src/main/scala/pl/immutables/akka/reasonable/downing/StaticQuorumDowning.scala#L117
https://github.com/mbilski/akka-reasonable-downing/blob/763613676fc5eb0d6c5e625c68ec8840b79f4e77/src/main/scala/pl/immutables/akka/reasonable/downing/StaticQuorumDowning.scala#L120
https://github.com/mbilski/akka-reasonable-downing/blob/763613676fc5eb0d6c5e625c68ec8840b79f4e77/src/main/scala/pl/immutables/akka/reasonable/downing/StaticQuorumDowning.scala#L135

Downing themselves (`cluster.down(cluster.selfUniqueAddress.address)`) should be enough, or?

**Comment by mbilski** [comment]
Fixed in #16
